import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
	home: {
		flex: 1,
	},
	container: {
		flex: 1,
	    backgroundColor: '#DBDEBC',
	    alignItems: 'center',
	    flexDirection: 'column',
	},
  	bgblock: {
  		height: 280,
  		width: Math.round(Dimensions.get('window').width),
  		backgroundColor: '#2FAA54',
	},
	title: {
		fontSize: 32,
		color: '#FFFFFF',
		textAlign: 'center',
		top: 20,
		zIndex: 1,
	},
	homecard: {
		top: 40,
		height: 220,
		width: 325,
		alignSelf: 'center',
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'column',
		backgroundColor: '#F9FFD2',
		borderRadius: 25,
	},
	logoicon: {
		alignSelf: 'center',
		height: 100,
		width: 100,
	},
	searchbar: {
		zIndex: 1,
		alignSelf: 'center',
		height: 40,
		width: 300,
		marginTop: 20,
		borderRadius: 25,
		backgroundColor: '#FFFFFF',
		borderWidth: 2,
		borderColor: '#000000',
	},
	inputText: {
	    fontSize: 18,
	    textAlign: 'left',
	    color: '#646464',
	    padding: 8,
	    marginLeft: 10,
  	},
  	itemlist: {
  		flex: 1,
	    flexDirection: 'column',
		top: 60,
		width: 325,
		borderRadius: 25,
		alignSelf: 'center',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F9FFD2',
		marginBottom: 80,
		paddingBottom: 40,
  	},
  	itemlistheader: {
  		flex: 1,
  		flexDirection: 'row',
  		alignItems: 'center',
  		height: 50,
  		width: 325,
  		backgroundColor: '#28712B',
  		borderTopLeftRadius: 25,
  		borderTopRightRadius: 25,
  	},
  	itemlisticon: {
  		alignSelf: 'flex-start',
		height: 40,
		width: 40,	
		marginLeft: 30,
		marginTop: 5,
  	},
  	itemlisttitle: {
  		fontSize: 18,
  		color: 'white',
  		marginLeft: 30,
  	},
  	sortsection: {
  		flex: 1,
  		flexDirection: 'row',
  		margin: 5,
  		alignItems: 'center',
  	},
  	pickerstyle: {
  		height: 40, 
  		width: 150,
  		backgroundColor: 'white',
  		borderRadius: 25,
  		borderWidth: 1,
  		justifyContent: 'center',
  	},
  	acctpickerstyle: {
  		height: 40, 
  		width: 130,
  		backgroundColor: 'white',
  		borderRadius: 25,
  		borderWidth: 1,
  		justifyContent: 'center',
  	},
  	itemcard: {
  		flex: 1,
  		flexDirection: 'row',
  		margin: 5,
  		alignItems: 'center',
  		height: 300,
  		width: 300,
  		backgroundColor: '#FBFFDF',
  		borderWidth: 1,
  		borderRadius: 8,
  	},
  	itemcardicon: {
  		height: 100,
  		width: 100,
  		margin: 10,
  	},
  	itemcardlist: {
  		flex: 1,
  		flexDirection: 'column',
  		marginLeft: 5,
  	},
  	itemcardtext1: {
  		fontSize: 18,
  		justifyContent: 'flex-start',
  		marginBottom: 5,
  	},
  	itemcardtext2: {
  		fontSize: 15,
  		justifyContent: 'flex-start',
  		color: 'green',
  		marginBottom: 5,
  	},
  	itemcardtext3: {
  		fontSize: 15,
  		justifyContent: 'flex-start',
  		marginBottom: 5,
  	},
  	itemcardtext4: {
  		fontSize: 15,
  		justifyContent: 'flex-start',
  		color: '#635EFF',
  		marginBottom: 5,
  	},
  	itemcardtext5: {
  		fontSize: 15,
  		justifyContent: 'flex-start',
  		color: 'red',
  	},
  	iteminfoicon: {
  		height: 50,
  		width: 30,
  		opacity: 0.5,
  		backgroundColor: '#000000',
  		borderRadius: 10,
  	},
  	tabIcon: {
  		height: 20,
  		width: 20,
  		resizeMode: 'contain',
  	},
  	infocard: {
	    flexDirection: 'column',
		top: 30,
		width: 325,
		borderRadius: 25,
		alignSelf: 'center',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F9FFD2',
		marginBottom: 80,
		paddingBottom: 20,
  	},
  	infocardheader: {
  		flexDirection: 'row',
  		alignItems: 'center',
  		height: 50,
  		width: 325,
  		backgroundColor: '#28712B',
  		borderTopLeftRadius: 25,
  		borderTopRightRadius: 25,
  		marginBottom: 20,
  	},
  	infoInput: {
  		flexDirection: 'row',
  		alignItems: 'center',
  		alignSelf: 'center',
  		justifyContent: 'center',
  	},
  	inputSection: {
	    borderWidth: 3,
	    width: 180,
	    height: 40,
	    borderBottomColor: '#707070',
	    borderTopColor: '#F9FFD2',
	    borderLeftColor: '#F9FFD2',
	    borderRightColor: '#F9FFD2',
	    flexDirection: 'row',
	    margin: 10,
	    alignItems: 'center',
  	},
  	inputIcon: {
  		alignSelf: 'flex-start',
  		resizeMode: 'contain',
		height: 40,
		width: 40,	
		marginLeft: 30,
		marginTop: 10,
  	},
  	infoInputText: {
	    fontSize: 18,
	    textAlign: 'left',
	    color: '#646464',
	    padding: 8,
  	},
  	genericButton: {
  		height: 60,
  		width: 240,
  		borderRadius: 30,
  		justifyContent: 'center',
  		alignItems: 'center',
  		margin: 20,
  		backgroundColor: 'blue',
  	},
  	test: {
  		flex: 1,
	    flexDirection: 'row',
  	},
	shadow: {
	  	shadowColor: '#000',
	  	shadowOffset: { width: 5, height: 10 },
	  	shadowOpacity: 1,
	  	shadowRadius: 8,
	  	elevation: 5,
	},
	testitem: {
		fontSize: 50,
	},
});
